# -*- coding: utf-8 -*-
"""apps-aruCo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FsZkKQb6xZXhq-UPtwGccOUhruYKutwC
"""
# lobaries
import streamlit as st
import cv2
import numpy as np
import skimage.io as io

# vars
plant = 'plant.png'

# main page
st.set_page_config(page_title='K-Means - Yedidya Harris', page_icon = plant, layout = 'wide', initial_sidebar_state = 'auto')
st.title('yuval chemke web-app')
